services:
  gateway:
    image: ${REGISTRY:-ghcr.io/codewithdripzy}/paygidi-gateway:latest
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ACCOUNT_SERVICE_URL=http://account-service:8080
      - WALLET_SERVICE_URL=http://wallet-service:8082
      - TRANSACTION_SERVICE_URL=http://transaction-service:8081
      - AI_SERVICE_URL=http://ai-service:8083
      - NOTIFICATION_SERVICE_URL=http://notification-service:8080
    depends_on:
      - account-service
      - wallet-service
      - transaction-service
      - ai-service
      - notification-service

  account-service:
    image: ${REGISTRY:-ghcr.io/codewithdripzy}/paygidi-account:latest
    build:
      context: .
      dockerfile: ./services/account/Dockerfile
    expose:
      - "8080"
      - "50051"
    env_file:
      - ./services/account/.env.production
    depends_on:
      - postgres

  wallet-service:
    image: ${REGISTRY:-ghcr.io/codewithdripzy}/paygidi-wallet:latest
    build:
      context: .
      dockerfile: ./services/wallet/Dockerfile
    expose:
      - "8082"
      - "50053"
    env_file:
      - ./services/wallet/.env.production
    depends_on:
      - postgres

  transaction-service:
    image: ${REGISTRY:-ghcr.io/codewithdripzy}/paygidi-transaction:latest
    build:
      context: .
      dockerfile: ./services/transaction/Dockerfile
    expose:
      - "8081"
      - "50055"
    env_file:
      - ./services/transaction/.env.production
    depends_on:
      - postgres

  ai-service:
    image: ${REGISTRY:-ghcr.io/codewithdripzy}/paygidi-ai:latest
    build:
      context: .
      dockerfile: ./services/ai/Dockerfile
    expose:
      - "8083"
      - "50054"
    env_file:
      - ./services/ai/.env.production
    depends_on:
      - postgres

  notification-service:
    image: ${REGISTRY:-ghcr.io/codewithdripzy}/paygidi-notification:latest
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    expose:
      - "8080"
      - "50052"
    env_file:
      - ./services/notification/.env.production
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - ./services/postgres/.env.production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
