services:
  gateway:
    image: ${DOCKER_HUB_USERNAME:-codewithdripzy}/paygidi-gateway:latest
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - account-service
      - wallet-service
      - transaction-service
      - ai-service
      - notification-service

  account-service:
    image: ${DOCKER_HUB_USERNAME:-codewithdripzy}/paygidi-account:latest
    build:
      context: .
      dockerfile: ./services/account/Dockerfile
    expose:
      - "50051"
    env_file:
      - ./services/account/.env
    depends_on:
      - postgres

  wallet-service:
    image: ${DOCKER_HUB_USERNAME:-codewithdripzy}/paygidi-wallet:latest
    build:
      context: .
      dockerfile: ./services/wallet/Dockerfile
    expose:
      - "50053"
    env_file:
      - ./services/wallet/.env
    depends_on:
      - postgres

  transaction-service:
    image: ${DOCKER_HUB_USERNAME:-codewithdripzy}/paygidi-transaction:latest
    build:
      context: .
      dockerfile: ./services/transaction/Dockerfile
    expose:
      - "50055"
    env_file:
      - ./services/transaction/.env
    depends_on:
      - postgres

  ai-service:
    image: ${DOCKER_HUB_USERNAME:-codewithdripzy}/paygidi-ai:latest
    build:
      context: .
      dockerfile: ./services/ai/Dockerfile
    expose:
      - "50054"
    env_file:
      - ./services/ai/.env
    depends_on:
      - postgres

  notification-service:
    image: ${DOCKER_HUB_USERNAME:-codewithdripzy}/paygidi-notification:latest
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    expose:
      - "50052"
    env_file:
      - ./services/notification/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - ./services/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
