basePath: /api/v1
host: localhost:8083
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the AI orchestration service for PayGidi KYB.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: PayGidi AI Service API
  version: "1.0"
paths: {}
swagger: "2.0"
