// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the profile details of the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get account details",
                "responses": {
                    "200": {
                        "description": "Account details",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete the authenticated user's account and all associated data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Delete account",
                "responses": {
                    "200": {
                        "description": "Account deleted successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/account/pin": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update the existing PIN for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Update account PIN",
                "parameters": [
                    {
                        "description": "PIN update data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.UpdatePinDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PIN updated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Set a new PIN for the authenticated user. Only works if no PIN is currently set.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Set account PIN",
                "parameters": [
                    {
                        "description": "PIN data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.SetPinDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PIN set successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "Initiate authentication (registration or login) via phone number. Sends an OTP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Initiate authentication",
                "parameters": [
                    {
                        "description": "Authentication data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.AuthDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP sent successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "User not found (if accountType missing)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "User already exists (if accountType provided)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "Too many OTP requests",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/biometric": {
            "post": {
                "description": "Exchange a biometric ID for a new JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Authenticate via biometrics",
                "parameters": [
                    {
                        "description": "Biometric authentication data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.BiometricAuthDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/biometric/register": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Link a biometric ID to the authenticated user's account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Enable biometric authentication",
                "parameters": [
                    {
                        "description": "Biometric registration data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.RegisterBiometricDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Biometrics enabled successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/complete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Finalize user or business account setup after phone verification.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Complete account registration",
                "parameters": [
                    {
                        "description": "Account data (either IndividualCompleteAccountDto or BusinessCompleteAccountDto)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Account completed successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Logs out the current user by clearing the auth cookie and invalidating sessions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "Logged out successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/otp/request/{otpType}": {
            "post": {
                "description": "Request an OTP to be sent via email or SMS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Request OTP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OTP type (email or phone)",
                        "name": "otpType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "OTP request data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.RequestOTPDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP sent successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "post": {
                "description": "Verify the OTP sent to the user's phone number and return JWT tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify authentication OTP",
                "parameters": [
                    {
                        "description": "OTP verification data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.VerifyAuthOtpDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid OTP or expired",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "OTP or User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/verify/bvn-image": {
            "post": {
                "description": "Verify a user's face image against their BVN record.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify BVN Image",
                "parameters": [
                    {
                        "description": "BVN and Image data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.VerifyBVNImageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "BVN image verified successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Image mismatch",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Service error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/verify/email": {
            "post": {
                "description": "Verify the OTP sent to the user's email address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify email OTP",
                "parameters": [
                    {
                        "description": "Email verification data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.VerifyEmailDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email verified successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid OTP or expired",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "User or OTP not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/verify/nin": {
            "post": {
                "description": "Verify a user's National Identification Number (NIN).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify NIN",
                "parameters": [
                    {
                        "description": "NIN data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.VerifyNINDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "NIN verified successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid NIN",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Service error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/business/docs": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update the verification documents for a business account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Business"
                ],
                "summary": "Update business documents",
                "parameters": [
                    {
                        "description": "Business documents data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.UpdateBusinessDocsDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Business documents updated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/business/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve the profile information for the authenticated business account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Business"
                ],
                "summary": "Get business profile",
                "responses": {
                    "200": {
                        "description": "Business profile retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update the profile information for a business account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Business"
                ],
                "summary": "Update business profile",
                "parameters": [
                    {
                        "description": "Business profile data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validators.UpdateBusinessProfileDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Business profile updated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check the health of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Fetch the profile details and associations of the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "Current user details",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Activity": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "description": "Nullable for soft deletes",
                    "type": "string"
                },
                "details": {
                    "description": "Additional details about the activity",
                    "type": "string"
                },
                "id": {
                    "description": "Unique identifier for the activity",
                    "type": "integer"
                },
                "ipAddress": {
                    "description": "IP address from which the activity was performed",
                    "type": "string"
                },
                "type": {
                    "description": "Type of activity (e.g., \"login\", \"logout\", \"update_profile\")",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "description": "Belongs to User",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "userAgent": {
                    "description": "User agent string for the activity",
                    "type": "string"
                },
                "userId": {
                    "description": "Reference to the user associated with the activity",
                    "type": "integer"
                }
            }
        },
        "models.AuthInfo": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastLoginAt": {
                    "description": "User            User       ` + "`" + `gorm:\"constraint:OnUpdate:CASCADE,OnDelete:SET NULL;\"` + "`" + ` // Belongs to User",
                    "type": "string"
                },
                "lockedReason": {
                    "type": "string"
                },
                "lockedUntil": {
                    "description": "Timestamp until which the user is locked out",
                    "type": "string"
                },
                "loginAttempts": {
                    "description": "Number of login attempts",
                    "type": "integer"
                },
                "otpCooldownUntil": {
                    "description": "Timestamp until which the user is cooled down from requesting OTP",
                    "type": "string"
                },
                "otpRequestCount": {
                    "description": "Number of OTP requests",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "description": "Unique identifier for the user",
                    "type": "integer"
                }
            }
        },
        "models.Business": {
            "type": "object",
            "properties": {
                "additionalDocs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "facebook": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "instagram": {
                    "type": "string"
                },
                "linkedIn": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registrationDoc": {
                    "description": "URL to the document",
                    "type": "string"
                },
                "registrationNumber": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "type": {
                    "description": "e.g., \"LLC\", \"Sole Proprietorship\"",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "models.ContactInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "postalCode": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "user": {
                    "description": "Belongs to User",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "models.KYC": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "document": {
                    "description": "base64 or URL to document",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kycType": {
                    "description": "e.g., \"passport\", \"nationalID\"",
                    "type": "string"
                },
                "status": {
                    "description": "\"pending\", \"approved\", \"rejected\"",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "description": "remove uniqueIndex, keep index for performance",
                    "type": "integer"
                }
            }
        },
        "models.OTP": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "forWhat": {
                    "description": "e.g., \"register\", \"login\", \"setPin\", \"updatePin\"",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                },
                "verified": {
                    "type": "boolean"
                },
                "via": {
                    "description": "sms, email, whatsapp",
                    "type": "string"
                }
            }
        },
        "models.Permission": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "e.g., \"read_account\", \"edit_user\"",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Person": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "otherNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "postalCode": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "userID": {
                    "description": "Make sure only one Person per User",
                    "type": "integer"
                }
            }
        },
        "models.Preference": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "description": "Nullable for soft deletes",
                    "type": "string"
                },
                "id": {
                    "description": "Unique identifier for the preference",
                    "type": "integer"
                },
                "language": {
                    "description": "e.g., \"en\", \"fr\", etc.",
                    "type": "string"
                },
                "notificationsEnabled": {
                    "description": "Indicates if notifications are enabled",
                    "type": "boolean"
                },
                "theme": {
                    "description": "e.g., \"light\", \"dark\"",
                    "type": "string"
                },
                "timezone": {
                    "description": "e.g., \"UTC\", \"America/New_York\"",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "description": "Description of the role",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "e.g., \"admin\", \"user\"",
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Permission"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Session": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "currentSessionID": {
                    "description": "Token for the current session",
                    "type": "string"
                },
                "expiresAt": {
                    "description": "Expiration time for the session",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastKnownIp": {
                    "description": "Last known IP address of the user",
                    "type": "string"
                },
                "lastUserAgent": {
                    "description": "User agent string for the session",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "description": "Belongs to User",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "userId": {
                    "description": "Reference to the user associated with the session",
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "email",
                "username"
            ],
            "properties": {
                "accountType": {
                    "description": "individual or business",
                    "type": "string"
                },
                "activities": {
                    "description": "List of activities performed by the user",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Activity"
                    }
                },
                "authInfo": {
                    "description": "Authentication-related information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AuthInfo"
                        }
                    ]
                },
                "biometricEnabled": {
                    "type": "boolean"
                },
                "biometricID": {
                    "description": "Unique identifier for biometrics (e.g., Device ID + Biometric Hash)",
                    "type": "string"
                },
                "business": {
                    "description": "Business-related information (if accountType is business)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Business"
                        }
                    ]
                },
                "contact": {
                    "description": "Contact information for the user",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ContactInfo"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "emailVerified": {
                    "description": "Indicates if the user's email is verified",
                    "type": "boolean"
                },
                "hashedNIN": {
                    "description": "Hashed version of the user's NIN for security",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isFirstTime": {
                    "description": "Indicates if this is the user's first login",
                    "type": "boolean"
                },
                "kycs": {
                    "description": "List of KYC documents associated with the user",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.KYC"
                    }
                },
                "otps": {
                    "description": "List of OTPs associated with the user",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OTP"
                    }
                },
                "person": {
                    "description": "One-to-one link",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Person"
                        }
                    ]
                },
                "phone": {
                    "type": "string"
                },
                "phoneVerified": {
                    "description": "Indicates if the user's phone number is verified",
                    "type": "boolean"
                },
                "pin": {
                    "description": "Hashed version of the user's PIN for security",
                    "type": "string"
                },
                "preferences": {
                    "description": "User preferences",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Preference"
                        }
                    ]
                },
                "profile_pic": {
                    "description": "URL to the user's profile picture",
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Role"
                    }
                },
                "sessions": {
                    "description": "List of active sessions for the user",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Session"
                    }
                },
                "status": {
                    "description": "e.g., \"active\", \"inactive\", etc.",
                    "type": "string"
                },
                "twoFactorEnabled": {
                    "description": "Indicates if two-factor authentication is enabled",
                    "type": "boolean"
                },
                "twoFactorMethod": {
                    "description": "Method of two-factor authentication (e.g., \"sms\", \"email\", \"app\")",
                    "type": "string"
                },
                "twoFactorSecret": {
                    "description": "Secret for two-factor authentication",
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3
                }
            }
        },
        "responses.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "validators.AuthDto": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "accountType": {
                    "type": "string",
                    "enum": [
                        "individual",
                        "business"
                    ]
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10
                }
            }
        },
        "validators.BiometricAuthDto": {
            "type": "object",
            "required": [
                "biometricID",
                "phone"
            ],
            "properties": {
                "biometricID": {
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10
                }
            }
        },
        "validators.RegisterBiometricDto": {
            "type": "object",
            "required": [
                "biometricID"
            ],
            "properties": {
                "biometricID": {
                    "type": "string"
                }
            }
        },
        "validators.RequestOTPDto": {
            "type": "object",
            "required": [
                "forWhat"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "forWhat": {
                    "type": "string",
                    "enum": [
                        "completeRegister",
                        "login",
                        "setPin",
                        "updatePin",
                        "twoFactorAuth"
                    ]
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10
                }
            }
        },
        "validators.SetPinDto": {
            "type": "object",
            "required": [
                "confirmPin",
                "pin"
            ],
            "properties": {
                "confirmPin": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                }
            }
        },
        "validators.UpdateBusinessDocsDto": {
            "type": "object",
            "properties": {
                "additionalDocs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "registrationDoc": {
                    "type": "string"
                }
            }
        },
        "validators.UpdateBusinessProfileDto": {
            "type": "object",
            "properties": {
                "businessType": {
                    "type": "string"
                },
                "facebook": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "instagram": {
                    "type": "string"
                },
                "linkedIn": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "registrationNumber": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 5
                },
                "twitter": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "validators.UpdatePinDto": {
            "type": "object",
            "required": [
                "confirmPin",
                "newPin",
                "oldPin"
            ],
            "properties": {
                "confirmPin": {
                    "type": "string"
                },
                "newPin": {
                    "type": "string"
                },
                "oldPin": {
                    "type": "string"
                }
            }
        },
        "validators.VerifyAuthOtpDto": {
            "type": "object",
            "required": [
                "otp",
                "phone"
            ],
            "properties": {
                "otp": {
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10
                }
            }
        },
        "validators.VerifyBVNImageDto": {
            "type": "object",
            "required": [
                "base64Image",
                "bvn"
            ],
            "properties": {
                "base64Image": {
                    "type": "string"
                },
                "bvn": {
                    "type": "string"
                }
            }
        },
        "validators.VerifyEmailDto": {
            "type": "object",
            "required": [
                "email",
                "forWhat",
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "forWhat": {
                    "type": "string",
                    "enum": [
                        "completeRegister",
                        "login",
                        "setPin",
                        "updatePin",
                        "twoFactorAuth"
                    ]
                },
                "otp": {
                    "type": "string",
                    "minLength": 4
                }
            }
        },
        "validators.VerifyNINDto": {
            "type": "object",
            "required": [
                "nin"
            ],
            "properties": {
                "nin": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.paygidi.site",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PayGidi Account Service API",
	Description:      "This is the account service for PayGidi.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
