basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the transaction service for PayGidi.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: PayGidi Transaction Service API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - Health
  /transactions/{customerIdentifier}:
    get:
      consumes:
      - application/json
      description: Fetch transaction history for a specific customer identifier using
        the Squad API.
      parameters:
      - description: Customer Identifier (e.g. email or UID)
        in: path
        name: customerIdentifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Get customer transactions
      tags:
      - Transactions
swagger: "2.0"
